# Generated by Django 4.0.4 on 2022-05-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_featured_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='featured_product_image',
            new_name='category_thumbnail',
        ),
        migrations.RemoveField(
            model_name='category',
            name='featured_product',
        ),
    ]
