# Generated by Django 4.0.4 on 2022-05-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_featured_product_image_category_category_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_thumbnail',
            field=models.ImageField(upload_to='category/images'),
        ),
    ]
